### ISSUE TITLE
azure_stateful_node: Module not idempotent

### ISSUE THREAD

**Issue by jfunke4** [spotinst/spot-ansible-cloud-modules#10]
**SUMMARY**
When I use the module to delete a VM from the spot.io configuration and Azure it works in the 1st run.
If I run the playbook again the task fails, with the error message below.

**ERROR**
TASK [spotio : spot.io: Delete VM] ***********************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed deleting stateful node - 'uniqueness_by' is set to 'name' but there is no stateful node with the name 'spot-test'"}

**EXPECTED BEHAVOIR**
When the VM is not present in spot.io, the task should result in a OK state and not fail.

**COMPONENT NAME**
spot.cloud_modules.azure_stateful_node 

**ADDITIONAL INFORMATION**

Ansible playbook:
```
- name: "spot.io: Delete VM"
  spot.cloud_modules.azure_stateful_node:
    token: "{{ var_role_spot_token }}"
    state: absent
    stateful_node_config:
      deletion_config:
        deallocation_config:
          disk_deallocation_config:
            should_deallocate: true
            ttl_in_hours: 0
          network_deallocation_config:
            should_deallocate: true
            ttl_in_hours: 0
          public_ip_deallocation_config:
            should_deallocate: true
            ttl_in_hours: 0
          snapshot_deallocation_config:
            should_deallocate: true
            ttl_in_hours: 0
          should_terminate_vm: true
    stateful_node:
      name: "spot-test"
      region: "westeurope"
      resource_group_name: "rg-test"
```
