### ISSUE TITLE
azure_statefule_node: Error encountered while creating statefulNode

### ISSUE THREAD

**Issue by jfunke4** [spotinst/spot-ansible-cloud-modules#11]
SUMMARY
I receive the error below, when I use the Azure module to create a stateful node.

ERROR
`The full traceback is:
Traceback (most recent call last):
  File "/home/jf/.ansible/tmp/ansible-tmp-1685524944.924535-28270-121695769538824/AnsiballZ_azure_stateful_node.py", line 107, in <module>
    _ansiballz_main()
  File "/home/jf/.ansible/tmp/ansible-tmp-1685524944.924535-28270-121695769538824/AnsiballZ_azure_stateful_node.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/jf/.ansible/tmp/ansible-tmp-1685524944.924535-28270-121695769538824/AnsiballZ_azure_stateful_node.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.spot.cloud_modules.plugins.modules.azure_stateful_node', init_globals=dict(_module_fqn='ansible_collections.spot.cloud_modules.plugins.modules.azure_stateful_node', _modlib_path=modlib_path),
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/ansible_spot.cloud_modules.azure_stateful_node_payload_9jxh_h3y/ansible_spot.cloud_modules.azure_stateful_node_payload.zip/ansible_collections/spot/cloud_modules/plugins/modules/azure_stateful_node.py", line 1292, in <module>
  File "/tmp/ansible_spot.cloud_modules.azure_stateful_node_payload_9jxh_h3y/ansible_spot.cloud_modules.azure_stateful_node_payload.zip/ansible_collections/spot/cloud_modules/plugins/modules/azure_stateful_node.py", line 1282, in main
  File "/tmp/ansible_spot.cloud_modules.azure_stateful_node_payload_9jxh_h3y/ansible_spot.cloud_modules.azure_stateful_node_payload.zip/ansible_collections/spot/cloud_modules/plugins/modules/azure_stateful_node.py", line 879, in handle_stateful_node
  File "/tmp/ansible_spot.cloud_modules.azure_stateful_node_payload_9jxh_h3y/ansible_spot.cloud_modules.azure_stateful_node_payload.zip/ansible_collections/spot/cloud_modules/plugins/modules/azure_stateful_node.py", line 952, in handle_create_stateful_node
  File "/home/jf/.local/lib/python3.11/site-packages/spotinst_sdk2/clients/stateful_node/__init__.py", line 33, in create_stateful_node
    response = self.send_post(
               ^^^^^^^^^^^^^^^
  File "/home/jf/.local/lib/python3.11/site-packages/spotinst_sdk2/client.py", line 160, in send_post
    self.handle_exception("creating {}".format(entity_name), result)
  File "/home/jf/.local/lib/python3.11/site-packages/spotinst_sdk2/client.py", line 278, in handle_exception
    raise SpotinstClientException(
spotinst_sdk2.client.SpotinstClientException: Error encountered while creating statefulNode
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/jf/.ansible/tmp/ansible-tmp-1685524944.924535-28270-121695769538824/AnsiballZ_azure_stateful_node.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/jf/.ansible/tmp/ansible-tmp-1685524944.924535-28270-121695769538824/AnsiballZ_azure_stateful_node.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/jf/.ansible/tmp/ansible-tmp-1685524944.924535-28270-121695769538824/AnsiballZ_azure_stateful_node.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.spot.cloud_modules.plugins.modules.azure_stateful_node', init_globals=dict(_module_fqn='ansible_collections.spot.cloud_modules.plugins.modules.azure_stateful_node', _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/tmp/ansible_spot.cloud_modules.azure_stateful_node_payload_9jxh_h3y/ansible_spot.cloud_modules.azure_stateful_node_payload.zip/ansible_collections/spot/cloud_modules/plugins/modules/azure_stateful_node.py\", line 1292, in <module>\n  File \"/tmp/ansible_spot.cloud_modules.azure_stateful_node_payload_9jxh_h3y/ansible_spot.cloud_modules.azure_stateful_node_payload.zip/ansible_collections/spot/cloud_modules/plugins/modules/azure_stateful_node.py\", line 1282, in main\n  File \"/tmp/ansible_spot.cloud_modules.azure_stateful_node_payload_9jxh_h3y/ansible_spot.cloud_modules.azure_stateful_node_payload.zip/ansible_collections/spot/cloud_modules/plugins/modules/azure_stateful_node.py\", line 879, in handle_stateful_node\n  File \"/tmp/ansible_spot.cloud_modules.azure_stateful_node_payload_9jxh_h3y/ansible_spot.cloud_modules.azure_stateful_node_payload.zip/ansible_collections/spot/cloud_modules/plugins/modules/azure_stateful_node.py\", line 952, in handle_create_stateful_node\n  File \"/home/jf/.local/lib/python3.11/site-packages/spotinst_sdk2/clients/stateful_node/__init__.py\", line 33, in create_stateful_node\n    response = self.send_post(\n               ^^^^^^^^^^^^^^^\n  File \"/home/jf/.local/lib/python3.11/site-packages/spotinst_sdk2/client.py\", line 160, in send_post\n    self.handle_exception(\"creating {}\".format(entity_name), result)\n  File \"/home/jf/.local/lib/python3.11/site-packages/spotinst_sdk2/client.py\", line 278, in handle_exception\n    raise SpotinstClientException(\nspotinst_sdk2.client.SpotinstClientException: Error encountered while creating statefulNode\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}`

EXPECTED BEHAVOIR
The creation of the stateful node in spot.io

COMPONENT NAME
spot.cloud_modules.azure_stateful_node

ADDITIONAL INFORMATION
ansible [core 2.14.6]
python version = 3.11.2 (main, Apr  5 2023, 11:57:00) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)] (/usr/bin/python3.11)
jinja version = 3.1.2

Ansible playbook:

```
  spot.cloud_modules.azure_stateful_node:
    state: present
    token: "{{ var_role_spot_token }}"
    uniqueness_by: "id"
    do_not_update:
      - region
      - resource_group_name        
    stateful_node:
      name: "test"
      description: "test"
      region: "westeurope"
      resource_group_name: "rg-euw-spotio"
      persistence:
        data_disks_persistence_mode: "reattach"
        os_disk_persistence_mode: "reattach"
        should_persist_data_disks: true
        should_persist_network: true
        should_persist_os_disk: true
      compute:
        os: "Linux"
        vm_sizes: 
          od_sizes: ["standard_d2s_v3"]
          spot_sizes: ["standard_d2s_v3"]
          preferred_spot_sizes: ["standard_d2s_v3"]
        launch_specification:
          image:
            marketplace:
              publisher: "Canonical"
              version: "latest"
              sku: "18.04-LTS"
              offer: "UbuntuServer"
          login:
            user_name: "ubuntu"
            ssh_public_key:  "1234"
          network:
            resource_group_name: "rg-euw-network"
            virtual_network_name: "vnet01"
            network_interfaces:
              - is_primary: true
                assign_public_ip: false
                subnet_name: "default_subnet"
          os_disk:
            size_g_b: 30
            type: "Standard_LRS"
  register: result
```
